name: Build FreeCAD AppImage
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1 * * *' # every Day at 01:00
permissions:
  actions: write
  contents: write
defaults:
  run:
    shell: bash
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  linux:
    runs-on: ubuntu-latest
    #timeout-minutes: 180
    steps:
    - name: Setup Env
      run: |
        #set -x
        #set -v
        LINK_REPO="realthunder/FreeCAD"
        THIS_REPO_DIR=${GITHUB_WORKSPACE}
        TOOLS_DIR=${THIS_REPO_DIR}/.github/tools
        APPIMAGETOOL="${TOOLS_DIR}/appimagetool-x86_64.AppImage"

        for i in LINK_REPO THIS_REPO_DIR TOOLS_DIR APPIMAGETOOL; do
          eval "r=\"\$$i\""
          echo "$i=$r" >> $GITHUB_ENV
        done

    - name: Check Releases and Skip Rest of Job if no new release
      id: Check_Releases
      run: |
        #set -x
        #set -v
        GetReleases()
         {
          # Holt alle Releases, filtert nach Datum >= 2024-10-03 und sortiert sie chronologisch
          gh release list -R "$1" --json tagName,publishedAt --limit 100 | \
          jq -r 'sort_by(.publishedAt) | .[] | select(.publishedAt >= "2024-10-03T00:00:00Z") | .tagName' > "$2"
         }

        # 1. Listen erzeugen
        GetReleases "$LINK_REPO" "Link.Releases"
        GetReleases "$GITHUB_REPOSITORY" "This.Releases"

        # 2. Die Versionen finden, die im fremden Repo sind, aber nicht in meinem
        NEW_VERSIONS=$(grep -vxFf This.Releases Link.Releases || true)

        # 3. Die älteste "neue" Version nehmen (erste Zeile der Differenz)
        VERSION=$(head -n 1 <<< "$NEW_VERSIONS")

        rm -f "./Link.Releases" "./This.Releases"
        
        if [[ -z "${VERSION}" ]]; then
          echo "No new release found. Skipping rest of workflow."
          echo "skip=true" >> $GITHUB_OUTPUT
         else
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "New release found: ${VERSION}"
          echo "skip=false" >> $GITHUB_OUTPUT
        fi

    - name: Clone this repository
      if: steps.Check_Releases.outputs.skip == 'false'
      uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}

    - name: Get FreeCAD AppImage
      if: steps.Check_Releases.outputs.skip == 'false'
      run: |
        #set -x
        #set -v
        
        VERSION_NR=${VERSION%%stable}
        IN_FILE=FreeCAD-Link-Stable-Linux-x86_64-py3.11-${VERSION_NR}.AppImage
        OUT_FILE=FreeCAD-Link-Stable-GN-${VERSION_NR}.AppImage
        
        wget -q https://github.com/realthunder/FreeCAD/releases/download/${VERSION}/${IN_FILE}
        chmod a+x ${IN_FILE}
        ./${IN_FILE} --appimage-extract >/dev/null
        cp ${TOOLS_DIR}/AppRun.Link squashfs-root/AppRun
        rm -f squashfs-root/usr/share/metainfo/org.freecadweb.FreeCAD.Link.appdata.xml
        ARCH=x86_64 ${APPIMAGETOOL} squashfs-root/ ${OUT_FILE} >/dev/null
        rm ${IN_FILE}
        rm -rf squashfs-root
        
        # Upload to GitHub Releases
        list=$(gh release list -R "$GITHUB_REPOSITORY" --json tagName | jq -r 'map(select(true))[] | (.tagName)');
        for i in $list; do
          if [[ "$i" = "${VERSION}" ]]; then
            gh release delete $VERSION -y
          fi
        done
        gh release create $VERSION *.AppImage* --title "$VERSION"

